#!/bin/bash
RADIOFILE='radio.lst'
if [[ "$(command -v mplayer)" == "" ]]; then
	echo "This program depends on mplayer."
	echo "Please install mplayer."
	exit -1;
fi
if [[ -e $RADIOFILE ]]; then
	RADIOS="$(cat $RADIOFILE)"
	for RADIO in $RADIOS; do
		IFS=', ' read -r -a RADIOOPT <<< "$RADIO"
		ARG="${RADIOOPT[0]}"
		ARGS="$ARGS $ARG"
		URL="${RADIOOPT[1]}"
		if [[ "$1" == "$ARG" ]]; then
			echo "[Listening to $ARG]"
			echo ""
			echo -e "\t[space]: pause"
			echo -e "\t[<-]: back"
			echo -e "\t[->]: forward"
			echo -e "\t[qq]: quit"
			mplayer "$URL" > /dev/null 2>&1
			exit 1;
		fi
	done
	if [[ "$1" == "" ]]; then
		echo "Usage: $0 [radioname]"
		echo "Radios: "
		echo -e "\t$ARGS"
	fi
else
	echo "radio.lst is missing, creating one..."
	echo '' > radio.lst
	echo "Please add your radio stations to radio.lst"
	echo "Use the format:"
	echo -e "\tname,url"
	echo -e "\tname,url"
	echo " "
fi

